import { type NextPage } from "next";
import Head from "next/head";
import Article from "~/components/Article";
import H1 from "~/components/H1";
import Main from "~/layouts/Main";

const articles = [
  {
    badge: "For editors",
    header: "Design on your Mac",
    paragraph:
      "Design, prototype, and illustrate in a truly native macOS app, online or offline. Work in private or collaborate with others, in real time.",
    image: "/article-first-default.avif",
    mobileImage: "/article-first-mobile.avif",
    moreImage: "/1ml.avif",
    moreText: "Everything you need to know about the Sketch <b>Mac app</b>",
    actionText: "Download for macOS",
    additional: {
      "Browse old versions": "https://www.sketch.com/releases/mac/",
      "Download Beta": "https://www.sketch.com/beta/",
    },
  },
  {
    badge: "For everyone",
    header: "Explore in your browser",
    paragraph:
      "Browse documents, inspect designs, export assets, discuss feedback, manage users, and invite guests — on any computer, in any browser.",
    image: "/article-second-default.avif",
    mobileImage: "/article-second-mobile.avif",
    moreImage: "/2ml.avif",
    moreText: "Everything you need to know about the Sketch <b>Web app</b>",
    actionText: "Open the web app",
  },
  {
    badge: "For everyone",
    header: "Preview on iPhone",
    paragraph:
      "View your documents on the go, play prototypes on a real device, and mirror designs as you edit them on your Mac.",
    image: "/article-third-default.avif",
    mobileImage: "/article-third-mobile.avif",
    actionText: "Download on the App Store",
    additional: {
      "Our iPhone app works exclusively with Workspace documents.": "",
    },
  },
];

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <section>
          <header>
            <H1>Every hero needs a sidekick. We have two.</H1>
            <p>
              Create with our award-winning macOS app, share your projects in the
              browser (on any platform), and take Sketch with you.
            </p>
          </header>
          <div>
            {articles.map((article, index) => (
              <Article
                key={index}
                badge={article.badge}
                header={article.header}
                paragraph={article.paragraph}
                image={article.image}
                mobileImage={article.mobileImage}
                moreImage={article.moreImage}
                moreText={article.moreText}
                actionText={article.actionText}
                additional={article.additional}
              />
            ))}
          </div>
        </section>
      </Main>
    </>
  );
};

export default Home;
